version: "3.8"

services:
    app:
        build: .
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - ./public:/app/public # Maps the upload folder for persistence
