services:
    chartnalyze_flask:
        container_name: chartnalyze_flask
        build: .
        image: chartnalyze_flask:latest
        env_file: .docker.env
        depends_on:
            - chartnalyze_mysql
            - chartnalyze_mongo
    chartnalyze_nginx:
        container_name: chartnalyze_nginx
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - chartnalyze_flask

    chartnalyze_mysql:
        container_name: chartnalyze_mysql
        image: mysql:9.1.0
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: chartnalyze
            MYSQL_ROOT_PASSWORD: 11112222
            MYSQL_ALLOW_EMPTY_PASSWORD: false
            MYSQL_USER: chartnalyze
            MYSQL_PASSWORD: 11112222
        ports:
            - "3307:3306"
        volumes:
            - chartnalyze_mysql_data:/var/lib/mysql

    chartnalyze_mongo:
        container_name: chartnalyze_mongo
        image: mongo:6.0
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 11112222
            MONGO_INITDB_DATABASE: chartnalyze
            MONGO_DATABASE: chartnalyze
            MONGO_USERNAME: chartnalyze
            MONGO_PASSWORD: 11112222
        ports:
            - "27018:27017"
        volumes:
            - ./docker/mongo/init:/docker-entrypoint-initdb.d
            - chartnalyze_mongo_data:/data/db

volumes:
    chartnalyze_mysql_data:
    chartnalyze_mongo_data:
