"""create users table

Revision ID: 2492258395c3
Revises: 
Create Date: 2025-04-26 12:54:44.434504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2492258395c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.CHAR(36), primary_key=True),
        sa.Column('name', sa.VARCHAR(50), nullable=True),
        sa.Column('birth_date', sa.Date, nullable=True),
        sa.Column('username', sa.VARCHAR(16), unique=True, nullable=False),
        sa.Column('email', sa.VARCHAR(50), unique=True, nullable=False),
        sa.Column('email_verified_at', sa.DateTime, nullable=True),
        sa.Column('password', sa.VARCHAR(255), nullable=False),
        sa.Column('created_at', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime),
    )
    pass


def downgrade():
    op.drop_table('users')
    pass
