"""create users table

Revision ID: 2492258395c3
Revises: 50c3059cc908
Create Date: 2025-04-26 12:54:44.434504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2492258395c3'
down_revision = '50c3059cc908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.CHAR(36), primary_key=True),
        sa.Column('country_id', sa.CHAR(26), sa.ForeignKey('countries.id'), nullable=True),
        sa.Column('name', sa.VARCHAR(50)),
        sa.Column('username', sa.VARCHAR(16), unique=True, nullable=False),
        sa.Column('birth_date', sa.Date),
        sa.Column('email', sa.VARCHAR(50), unique=True, nullable=False),
        sa.Column('email_verified_at', sa.DateTime),
        sa.Column('password', sa.VARCHAR(255), nullable=False),
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, server_onupdate=sa.func.now()),
    )
    pass


def downgrade():
    op.drop_table('users')
    pass
